services:
    nil_portugues.api.mapping.mapper:
          class: NilPortugues\Api\Mapping\Mapper
          arguments: []

    nil_portugues.api.hal_json.hal_json_transformer:
         class: NilPortugues\Api\Hal\JsonTransformer
         arguments:
            - "@nil_portugues.api.mapping.mapper"

    nil_portugues.serializer.hal_json_serializer:
         class: NilPortugues\Symfony\HalJsonBundle\Serializer\HalJsonSerializer
         arguments:
            - "@nil_portugues.api.hal_json.hal_json_transformer"
            - "@router"
